### ISSUE TITLE
As a Judge I would like to vote on individual student submissions using a yes / no / maybe scale so that we can decide which submissions will be invited to the show.

### ISSUE THREAD

**Issue by robmcl4** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#24]
As a Judge I would like to vote on individual student submissions using a yes / no / maybe scale so that we can decide which submissions will be invited to the show.

**Comment by billdybas** [comment]
Verify the scoring system we are using.

Order on screen is:

N  M  Y

because Y is closest to the right arrow – we think they accept more than they reject.

Show them as radio buttons, empty to start. (Or populated w/ a previous vote per #25)

When you click on one, show a toast in the bottom right of the screen that says "Vote Saved"

Do not automatically go to the next entry in the queue, as a judge may hesitate on an entry, choose a vote, then change it – we don't want to interrupt their concentration or annoy them.
